//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  MembershipFunction                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Interface for any membership function   //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package membership;

public interface MembershipFunction {
	public double compute(double x);
}
